import { Dimensions, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import React from 'react'
import Header from '../../../Components/Header'
import WholeButton1 from '../../../Components/WholeButton1';


const { height, width } = Dimensions.get('window');
const VerifyAuthenticator = (props) => {
    return (
        <SafeAreaView style={{ flex: 1, backgroundColor: '#1C1D22' }}>
            <View style={styles.mainviewStyle}>
                <Header
                    navigate={() => props.navigation.goBack()}
                />
                <Text style={styles.logintext}>Verify Authenticator</Text>
                <Text style={styles.signStyle}>Enter the 6-digit code generated by the Authenticator App</Text>
                <Text style={styles.account}>Authenticator App Code</Text>
                <View style={{ marginTop: '5%', backgroundColor: 'rgba(34, 35, 42, 1)', padding: '4%', borderRadius: 7 }}>
                    <TouchableOpacity><Text style={{ alignSelf: 'flex-end', color: '#768C5C', fontSize: 14, fontWeight: '500', marginVertical: '3%' }}>Paste</Text>
                    </TouchableOpacity>
                   
                </View>

                <WholeButton1 Label={'Submit'} Action={()=>{props.navigation.naviagte('')}} styles={{ width: width * 0.9,marginTop:height*0.5 }} />
            </View>

        </SafeAreaView>
    )
}

export default VerifyAuthenticator

const styles = StyleSheet.create({
    mainviewStyle: {
        justifyContent: 'center',
        width: width * 0.9,
        alignSelf: 'center',

    },
    logintext: {
        fontSize: 32,
        fontWeight: '600',
        color: '#fff',
        marginTop: '20%',
        lineHeight: 32.97,
    },
    signStyle: {
        fontSize: 12,
        fontWeight: '400',
        color: 'rgba(255, 255, 255, 0.6)',
        lineHeight: 20,
        marginTop: 7,
    },
    account: {
        fontSize: 12,
        fontWeight: '400',
        color: 'rgba(255, 255, 255, 0.6)',
        lineHeight: 20,
        marginTop: '10%'
    },
})